import Foundation

// MARK: - Human-facing GFM export (#5 / old #102)

/// Builds a derived GitHub-flavored Markdown monolith from assembled sources.
/// Sources remain canonical; this file is for PRs, wikis, and human review.
enum MarkdownExporter {
    /// Default path when `build.markdown_export` is unset / defaulted in config.
    static let defaultOutputPath = "output/export.md"

    struct Options: Sendable {
        var input: String? = nil
        var output: String? = nil
        var skipAssets: Bool = false
        var skipHeadingNumbers: Bool = false
        var skipToc: Bool = false
    }

    struct Result: Sendable {
        let outputPath: String
        let absoluteOutputPath: String
        let copiedAssetCount: Int
        let outputRootPath: String
    }

    /// Assemble, render, optionally publish assets, and write the derived GFM file.
    @discardableResult
    static func export(project: SpecticusProject, options: Options = Options()) throws -> Result {
        var markdown = try DocumentGenerator.assembleSources(
            input: options.input,
            baseDirectory: project.root.path,
            fallbackInput: project.config.build.defaultInput,
            layout: project.assemblyLayout
        )

        let headingMax = options.skipHeadingNumbers ? 0 : project.config.build.headingNumberMaxLevel
        if headingMax > 0 {
            markdown = HeadingNumberer.numberHeadings(in: markdown, maxLevel: headingMax)
        }

        let tocMax: Int = {
            if options.skipToc || !project.config.build.tocEnabled { return 0 }
            return project.config.build.tocMaxLevel
        }()

        var gfm = render(
            markdown: markdown,
            title: project.documentTitle,
            tocMaxLevel: tocMax
        )

        let copyAssets = project.config.build.copyAssets && !options.skipAssets
        // Share the HTML output tree (css/img/svg) so build + export stay consistent (#9 / #5).
        let publish = try ResourcePublisher.publish(
            projectRoot: project.root,
            outputHTMLPath: project.defaultOutputPath,
            sourceCSS: project.styleSheetPath,
            diagramsDir: project.config.build.diagramsDir,
            copyAssets: copyAssets
        )
        gfm = rewriteReferences(in: gfm, rewrites: publish.pathRewrites)

        let outputPath = options.output ?? project.config.build.markdownExport
        let absolute = project.resolve(outputPath).path
        try DocumentGenerator.writeOutput(gfm, to: absolute)

        return Result(
            outputPath: outputPath,
            absoluteOutputPath: absolute,
            copiedAssetCount: publish.copiedDescriptions.count,
            outputRootPath: publish.outputRoot.path
        )
    }

    /// Render a reviewable GFM document.
    /// - Parameters:
    ///   - markdown: Assembled (and optionally heading-numbered) source Markdown.
    ///   - title: Document title from title.yml / config (for the banner only).
    ///   - tocMaxLevel: Max ATX level in the Contents list (0 = omit TOC).
    /// - Note: Owning IDs stay in headings (`## BR1: Title`) so reviewers can see them in GFM.
    ///   HTML chips (#149) are HTML-only presentation.
    static func render(
        markdown: String,
        title: String,
        tocMaxLevel: Int = TableOfContents.defaultMaxLevel
    ) -> String {
        var parts: [String] = []

        parts.append(
            "<!-- Generated by `scs export markdown`. Derived artifact — edit sources, then re-export (#5). -->"
        )
        parts.append("")

        let trimmedTitle = title.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmedTitle.isEmpty {
            let safe = escapeMarkdownEmphasis(trimmedTitle)
            parts.append(
                "> Derived GFM export of **\(safe)**. Sources are canonical; regenerate with `scs export markdown` (#5)."
            )
            parts.append("")
        }

        let tocLevel = TableOfContents.clampMaxLevel(tocMaxLevel)
        if tocLevel > 0 {
            let headings = TableOfContents.extractHeadings(from: markdown, maxLevel: tocLevel)
            let toc = renderMarkdownTOC(headings: headings)
            if !toc.isEmpty {
                parts.append(toc)
                parts.append("")
            }
        }

        let body = markdown.trimmingCharacters(in: .whitespacesAndNewlines)
        if !body.isEmpty {
            parts.append(body)
            parts.append("")
        }

        return parts.joined(separator: "\n")
    }

    /// GFM Contents list with the same slugs / ID preference as the HTML TOC (#12 / #149).
    static func renderMarkdownTOC(headings: [TableOfContents.Heading]) -> String {
        let entries = headings.filter { $0.id != nil }
        guard !entries.isEmpty else { return "" }

        var lines: [String] = ["## Contents", ""]
        for entry in entries {
            guard let id = entry.id else { continue }
            let indent = String(repeating: "  ", count: max(0, entry.level - 1))
            let label = escapeLinkLabel(entry.text)
            lines.append("\(indent)- [\(label)](#\(id))")
        }
        return lines.joined(separator: "\n")
    }

    /// Rewrite Markdown image / link destinations using the same map as HTML asset publish (#9).
    static func rewriteReferences(in markdown: String, rewrites: [String: String]) -> String {
        guard !rewrites.isEmpty else { return markdown }

        let sorted = rewrites.keys.sorted { $0.count > $1.count }
        var result = markdown

        for original in sorted {
            guard let replacement = rewrites[original], original != replacement else { continue }
            let escaped = NSRegularExpression.escapedPattern(for: original)
            // ![alt](path) or [text](path) — destination only (not reference-style defs for MVP).
            let pattern = #"(!?\[[^\]]*\]\()\#(escaped)(\))"#
            guard let regex = try? NSRegularExpression(pattern: pattern) else { continue }
            let range = NSRange(result.startIndex..., in: result)
            result = regex.stringByReplacingMatches(
                in: result,
                options: [],
                range: range,
                withTemplate: "$1\(NSRegularExpression.escapedTemplate(for: replacement))$2"
            )
        }
        return result
    }

    /// Sibling default: `output/index.html` → `output/export.md`.
    /// Uses string path ops so relative inputs stay relative (no CWD resolution).
    static func defaultPathBesideHTML(_ htmlOutput: String) -> String {
        let ns = htmlOutput as NSString
        let parent = ns.deletingLastPathComponent
        if parent.isEmpty || parent == "." {
            return "export.md"
        }
        return (parent as NSString).appendingPathComponent("export.md")
    }

    // MARK: - Escaping

    private static func escapeLinkLabel(_ text: String) -> String {
        text
            .replacingOccurrences(of: "[", with: "\\[")
            .replacingOccurrences(of: "]", with: "\\]")
    }

    private static func escapeMarkdownEmphasis(_ text: String) -> String {
        // Keep titles readable; escape bare asterisks that would break **title**.
        text.replacingOccurrences(of: "*", with: "\\*")
    }
}
